### ISSUE TITLE
webapicontrib.com

### ISSUE THREAD

**Issue by abatishchev** [WebApiContrib/webapicontrib.github.com#2]
Maybe add a regular domain to the github hosted pages? Like [webapicontrib.com](http://webapicontrib.com), It seems to be [available](http://www.who.is/whois/WebApiContrib.com).

**Comment by abatishchev** [comment]
Any thoughts?

**Comment by ChrisMissal** [comment]
For as little content as we have there I don't believe it's necessary to have the nice domain name.
